In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
import seaborn as sns

In [2]:
complete_df = pd.read_csv("Complete dataframe/data_preprocessing.csv")
complete_df["Datetime"] = pd.to_datetime(complete_df["Datetime"])
complete_df = complete_df.set_index("Datetime")
complete_df_2021_2022 = complete_df.loc['2021':'2022'].drop(columns=['Year'])
complete_df_2021_2022.head()

,Location,Visits,Date,Time,Journeys,Windspeed,Temperature,Clouds,Rain amount,Rain duration,...,Holiday_Name_Summer holiday,Holiday_Name_Whit,Holiday_Name_Winter holiday,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline,stringency_index
Datetime,,,,,,,,,,,,,,,,,,,,,
2021-01-01,Amstelpark,25.0,2021-01-01,00:00:00,21.818182,2.0,-0.4,1.0,0.0,0.0,...,0,0,1,-84.0,-64.0,-41.0,-80.0,-81.0,23.0,78.7
2021-01-01,Beatrixpark,154.0,2021-01-01,00:00:00,88.000000,2.0,-0.4,1.0,0.0,0.0,...,0,0,1,-84.0,-64.0,-41.0,-80.0,-81.0,23.0,78.7
2021-01-01,Erasmuspark,323.0,2021-01-01,00:00:00,13.933333,2.0,-0.4,1.0,0.0,0.0,...,0,0,1,-84.0,-64.0,-41.0,-80.0,-81.0,23.0,78.7
2021-01-01,Flevopark,65.0,2021-01-01,00:00:00,61.777778,2.0,-0.4,1.0,0.0,0.0,...,0,0,1,-84.0,-64.0,-41.0,-80.0,-81.0,23.0,78.7
2021-01-01,Gaasperpark,25.0,2021-01-01,00:00:00,15.400000,2.0,-0.4,1.0,0.0,0.0,...,0,0,1,-84.0,-64.0,-41.0,-80.0,-81.0,23.0,78.7

In [15]:
# Linear regression
X = np.array(complete_df_2021_2022.loc[:, 'Journeys' : 'stringency_index'])
y = np.array(complete_df_2021_2022.loc[:, "Visits"]).reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

regressor = LinearRegression()

regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)

y_test.reshape(-1)

predictions_actual = pd.DataFrame({'Actual': y_test.reshape(-1), 'Predicted': y_pred.reshape(-1)})

rmse = np.sqrt(mean_squared_error(predictions_actual['Actual'], predictions_actual['Predicted']))
mae = mean_absolute_error(predictions_actual['Actual'], predictions_actual['Predicted'])
print("RMSE : % f" %(rmse))
print("MAE : % f" %(mae))

RMSE :  191.641729
MAE :  122.309099

In [8]:
predictions_actual

        Actual   Predicted
0         72.0  198.001444
1        521.0  193.322065
2         40.0  133.948415
3        368.0  177.749762
4        572.0  246.181740
...        ...         ...
127454   428.0  342.038465
127455   201.0  133.948415
127456   102.0  127.064330
127457    84.5  133.948415
127458   607.0  230.793309

[127459 rows x 2 columns]