In [1]:
import glob
import numpy as np
import pandas as pd
from datetime import timedelta
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings(action='once')

In [2]:
df = pd.read_csv('resono_parks.csv')

In [3]:
df1 = df.drop(['Unnamed: 0', 'Locationcode', 'End_Dates', 'End_Time', 'End'], axis=1)
df1.drop_duplicates(inplace=True)
df1.reset_index(inplace=True, drop=True)
df1['Start'] = pd.to_datetime(df1['Start'], utc=True)
df1['Start'] = pd.to_datetime(df1['Start'].dt.strftime("%Y-%m-%d %H:%M:%S"))

In [4]:
df1['End'] = df1['Start'] + dt.timedelta(minutes=15, seconds=0)
df1.drop('Start', axis=1, inplace=True)

In [5]:
df1 = df1.rename({'Start_Dates': 'End_Dates', 'Start_Time' : 'End_Time'},
                                                   axis=1) 
df_average_visits = df1.copy() 
df_average_visits = df_average_visits.groupby(['Location', 'End']).mean().reset_index()

In [6]:
df_average_visits['Visits'] = df_average_visits["Visits"].astype(int)

In [7]:
resono_data = df_average_visits.copy()

In [8]:
resono_data['End_Dates'] = pd.to_datetime(resono_data['End']).dt.date
resono_data['End_Time'] = pd.to_datetime(resono_data['End']).dt.time

In [9]:

resono_data = resono_data[resono_data.Location != 'Frankendael']
resono_data.groupby('Location').count()

                       End  Visits  End_Dates  End_Time
Location
Amstelpark           38021   38021      38021     38021
Beatrixpark          38021   38021      38021     38021
Erasmuspark          42128   42128      42128     42128
Flevopark            38022   38022      38022     38022
Gaasperpark          38021   38021      38021     38021
Nelson Mandelapark   38021   38021      38021     38021
Noorderpark          38021   38021      38021     38021
Oosterpark           42128   42128      42128     42128
Park Frankendael     38021   38021      38021     38021
Rembrandtpark Noord   4159    4159       4159      4159
Rembrandtpark Zuid    4159    4159       4159      4159
Sarphatipark         42129   42129      42129     42129
Sloterpark           38022   38022      38022     38022
Vondelpark Oost      18092   18092      18092     18092
Vondelpark Oost 1    22113   22113      22113     22113
Vondelpark Oost 2    22113   22113      22113     22113
Vondelpark Oost 3    22112   22112      22112     22112
Vondelpark West      42129   42129      42129     42129
W.H. Vliegenbos      38021   38021      38021     38021
Westergasfabriek     36834   36834      36834     36834
Westerpark           13985   13985      13985     13985
Westerpark Centrum   22112   22112      22112     22112
Westerpark Oost      22112   22112      22112     22112
Westerpark West      22112   22112      22112     22112

In [10]:
resono_data.to_csv('test.csv')

In [11]:
df_new = pd.read_csv('test.csv')
df_new

,Unnamed: 0,Location,End,Visits,End_Dates,End_Time
0,0,Amstelpark,2020-11-12 00:15:00,15,2020-11-12,00:15:00
1,1,Amstelpark,2020-11-12 00:30:00,15,2020-11-12,00:30:00
2,2,Amstelpark,2020-11-12 00:45:00,11,2020-11-12,00:45:00
3,3,Amstelpark,2020-11-12 01:00:00,8,2020-11-12,01:00:00
4,4,Amstelpark,2020-11-12 01:15:00,3,2020-11-12,01:15:00
...,...,...,...,...,...,...
720603,734616,Westerpark West,2022-01-06 13:45:00,116,2022-01-06,13:45:00
720604,734617,Westerpark West,2022-01-06 14:00:00,107,2022-01-06,14:00:00
720605,734618,Westerpark West,2022-01-06 14:15:00,112,2022-01-06,14:15:00
720606,734619,Westerpark West,2022-01-06 14:30:00,114,2022-01-06,14:30:00
720607,734620,Westerpark West,2022-01-06 14:45:00,91,2022-01-06,14:45:00

In [4]:
df.groupby('Location').count()

,Unnamed: 0,Locationcode,Start,End,Visits,Start_Dates,Start_Time,End_Dates,End_Time
Location,,,,,,,,,
Erasmuspark,67898,67898,67898,67898,67898,67898,67898,67898,67898
Oosterpark,54210,54210,54210,54210,54210,54210,54210,54210,54210
Rembrandtpark Noord,12480,12480,12480,12480,12480,12480,12480,12480,12480
Rembrandtpark Zuid,11641,11641,11641,11641,11641,11641,11641,11641,11641
Sarphatipark,53558,53558,53558,53558,53558,53558,53558,53558,53558
Vondelpark Oost,42751,42751,42751,42751,42751,42751,42751,42751,42751
Vondelpark Oost 1,22113,22113,22113,22113,22113,22113,22113,22113,22113
Vondelpark Oost 2,22113,22113,22113,22113,22113,22113,22113,22113,22113
Vondelpark Oost 3,22112,22112,22112,22112,22112,22112,22112,22112,22112
Vondelpark West,55309,55309,55309,55309,55309,55309,55309,55309,55309
Westergasfabriek,41403,41403,41403,41403,41403,41403,41403,41403,41403
Westerpark,24213,24213,24213,24213,24213,24213,24213,24213,24213
Westerpark Centrum,22112,22112,22112,22112,22112,22112,22112,22112,22112
Westerpark Oost,22112,22112,22112,22112,22112,22112,22112,22112,22112
Westerpark West,22112,22112,22112,22112,22112,22112,22112,22112,22112